#!/usr/bin/env node

const fs = require('fs')
const path = require('path')

if (
  !fs.existsSync(path.resolve(__dirname, '../src/config/localOverrides.ts'))
) {
  console.log('Creating localOverrides...')
  fs.writeFileSync(
    path.resolve(__dirname, '../src/config/localOverrides.ts'),
    `import { Config } from './types'

const localConfig: Partial<Config> = {}

export default localConfig
`
  )
}
